IVSource/Models/IvsVisaCountriesDiplomaticRepresentation.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Serialization;

namespace IVSource.Models
{
    public partial class IvsVisaCountriesDiplomaticRepresentation  : MemberPageBase
    {
        [XmlIgnore]
        [JsonIgnore]
        [Display(Name = "Serial No.")]
        public int SerialNum { get; set; }
        [XmlIgnore]
        [JsonIgnore]
        public string CountryIso { get; set; }
        [XmlIgnore]
        [JsonIgnore]
        public string OfficeId { get; set; }
        [Required]
        [Display(Name = "Address")]
        [XmlElement("Address")]
        [JsonProperty("Address")]
        public string OfficeAddress { get; set; }
        [Required]
        [Display(Name = "City")]
        [XmlElement("City")]
        [JsonProperty("City")]

        public string OfficeCity { get; set; }
        [Required]
        [Display(Name = "Collection Timings")]
        [XmlElement("CollectionTimings")]
        [JsonProperty("CollectionTimings")]

        public string OfficeCollectionTimings { get; set; }
        [Required]
        [Display(Name = "Country")]
        [XmlElement("Country")]
        [JsonProperty("Country")]

        public string OfficeCountry { get; set; }
        [Required]
        [Display(Name = "Email")]
        [XmlElement("Email")]
        [JsonProperty("Email")]
        public string OfficeEmail { get; set; }
        [Display(Name = "Fax")]
        [XmlElement("Fax")]
        [JsonProperty("Fax")]
        public string OfficeFax { get; set; }
        [Required]
        [Display(Name = "Name")]
        [XmlElement("Name")]
        [JsonProperty("Name")]
        public string OfficeName { get; set; }
        [Display(Name = "Notes")]
        [XmlElement("Notes")]
        [JsonProperty("Notes")]
        public string OfficeNotes { get; set; }
        [Required]
        //[RegularExpression("([0-9]{10})$", ErrorMessage = "Invalid Phone Number.")]
        [Display(Name = "Phone")]
        [XmlElement("Phone")]
        [JsonProperty("Phone")]
        public string OfficePhone { get; set; }
        [Display(Name = "Pin Code")]
        [XmlElement("PinCode")]
        [JsonProperty("PinCode")]
        public string OfficePincode { get; set; }
        [Display(Name = "Public Timings")]
        [XmlElement("PublicTimings")]
        [JsonProperty("PublicTimings")]
        public string OfficePublicTimings { get; set; }

        [Display(Name = "Telephone Visa")]
        [XmlElement("Telephone")]
        [JsonProperty("Telephone")]
        public string OfficeTelephoneVisa { get; set; }

        [Required]
        [Display(Name = "Timings")]
        [XmlElement("Timings")]
        [JsonProperty("Timings")]
        public string OfficeTimings { get; set; }
        [Required]
        [Display(Name = "Visa Timings")]
        [XmlElement("VisaTimings")]
        [JsonProperty("VisaTimings")]
        public string OfficeVisaTimings { get; set; }
        [Display(Name = "Website")]
        [Url]
        [XmlElement("Website")]
        [JsonProperty("Website")]
        public string OfficeWebsite { get; set; }

        [Display(Name = "Territory Jurisdiction")]
        [XmlIgnore]
        [JsonIgnore]
        public string TerritoryJurisdiction { get; set; }
        [Required]
        [Display(Name = "Enable")]
        [XmlIgnore]
        [JsonIgnore]
        public int? IsEnable { get; set; }
        [XmlIgnore]
        [JsonIgnore]
        public string Priority { get; set; }
        [XmlIgnore]
        [JsonIgnore]
        public DateTime? CreatedDate { get; set; }
        [XmlIgnore]
        [JsonIgnore]
        public DateTime? ModifiedDate { get; set; }
    }
}

IVSource/Controllers/IvsVisaCountriesDiplomaticRepresentationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IVSource.Models;
using ReflectionIT.Mvc.Paging;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Configuration;
using AllPageLogout.Filter;

namespace IVSource.Controllers
{
    //[Authorize(Roles = MemberType.MemberAdmin, AuthenticationSchemes = MemberType.MemberAdminAuth)]
    public class IvsVisaCountriesDiplomaticRepresentationsController : Controller
    {
        private readonly IVSourceContext _context;

        public IvsVisaCountriesDiplomaticRepresentationsController(IVSourceContext context)
        {
            _context = context;
        }

        // GET: IvsVisaCountriesDiplomaticRepresentations
        public async Task<IActionResult> Index(string filter, string rowsToShow = "10", int page = 1, string sortExpression = "SerialNum")
        {
            var allList = _context.IvsVisaCountriesDiplomaticRepresentation.Where(x => x.CountryIso == TempData.Peek("CountryIso").ToString());

            if (!string.IsNullOrWhiteSpace(filter))
            {
                allList = allList.Where(p => filter.ToLower() == "yes" ? (p.IsEnable == 1) : (filter.ToLower() == "no" ? (p.IsEnable == 0) :
                        (p.OfficeName.Contains(filter) || p.OfficeCity.Contains(filter) || p.OfficeCountry.Contains(filter)))).OrderByDescending(y => y.SerialNum);
            }
            else
                allList = allList.OrderByDescending(y => y.SerialNum);

            int count = allList.Count();
            ViewBag.Total = count;

            var model = await PagingList<IvsVisaCountriesDiplomaticRepresentation>.CreateAsync(allList, Convert.ToInt16(rowsToShow), page, sortExpression, "SerialNum");
            model.RouteValue = new RouteValueDictionary { { "filter", filter }, { "rowsToShow", rowsToShow } };
            return View(model);
        }

        // GET: IvsVisaCountriesDiplomaticRepresentations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ivsVisaCountriesDiplomaticRepresentation = await _context.IvsVisaCountriesDiplomaticRepresentation.FindAsync(id);
            if (ivsVisaCountriesDiplomaticRepresentation == null)
            {
                return NotFound();
            }
            return View(ivsVisaCountriesDiplomaticRepresentation);
        }

        // POST: IvsVisaCountriesDiplomaticRepresentations/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, string CountryName, [Bind("SerialNum,CountryIso,OfficeId,OfficeName,OfficeAddress,OfficeCity,OfficePincode,OfficeCountry,OfficePhone,OfficeTelephoneVisa,OfficeFax,OfficeTimings,OfficeVisaTimings,OfficePublicTimings,OfficeCollectionTimings,OfficeEmail,OfficeWebsite,OfficeNotes,TerritoryJurisdiction,IsEnable,Priority,CreatedDate,ModifiedDate")] IvsVisaCountriesDiplomaticRepresentation ivsVisaCountriesDiplomaticRepresentation)
        {
            if (id != ivsVisaCountriesDiplomaticRepresentation.SerialNum)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    ivsVisaCountriesDiplomaticRepresentation.ModifiedDate = DateTime.Now;
                    _context.Update(ivsVisaCountriesDiplomaticRepresentation);
                    _context.Entry(ivsVisaCountriesDiplomaticRepresentation).Property(x => x.SerialNum).IsModified = false;
                    _context.Entry(ivsVisaCountriesDiplomaticRepresentation).Property(x => x.CountryIso).IsModified = false;
                    _context.Entry(ivsVisaCountriesDiplomaticRepresentation).Property(x => x.OfficeId).IsModified = false;
                    _context.Entry(ivsVisaCountriesDiplomaticRepresentation).Property(x => x.CreatedDate).IsModified = false;

                    var upCountry = _context.IvsVisaCountries.Where(y => y.CountryName == CountryName).FirstOrDefault();
                    upCountry.IsUpdated = 1;

                    upCountry.ModifiedDate = DateTime.Now;
                    _context.Update(upCountry);

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IvsVisaCountriesDiplomaticRepresentationExists(ivsVisaCountriesDiplomaticRepresentation.SerialNum))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["Message"] = "Updated Successfully!";
                return RedirectToAction("Index");
            }
            return View(ivsVisaCountriesDiplomaticRepresentation);
        }

        private bool IvsVisaCountriesDiplomaticRepresentationExists(int id)
        {
            return _context.IvsVisaCountriesDiplomaticRepresentation.Any(e => e.SerialNum == id);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(IvsVisaCountriesDiplomaticRepresentation obj)
        {
            string country = TempData.Peek("CountryName").ToString();
            var countryIso = _context.IvsVisaCountries.FirstOrDefault(x => x.CountryName == country);

            var ran = RandomString(8);

            var oid = ran;

            obj.CountryIso = countryIso.CountryIso;
            obj.OfficeId = countryIso.CountryIso + oid;
            obj.CreatedDate = DateTime.Now;

            _context.IvsVisaCountriesDiplomaticRepresentation.Add(obj);
            _context.SaveChanges();
            TempData["Message"] = "Inserted Successfully!";
            return RedirectToAction("../IvsVisaCountriesDiplomaticRepresentations/Index");
        }

        Random random = new Random();
        public string RandomString(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length).Select(s => s[random.Next(s.Length)]).ToArray());
        }
    }
    //[Authorize(Roles = MemberType.MemberUser, AuthenticationSchemes = MemberType.MemberUserAuth)]
    public class IvsVisaCountriesDiplomaticRepr_UserController : Controller
    {
        private readonly IVSourceContext _context;
        public IConfiguration _Configuration { get; }

        public IvsVisaCountriesDiplomaticRepr_UserController(IVSourceContext context, IConfiguration iconfiguration)
        {
            _context = context;
            _Configuration = iconfiguration;
        }
        [CustemFilter]
        public IActionResult DiplomaticRepresentation(string countryName, string countryFlag)
        {
            var listPages = _context.IvsVisaPages.Where(x => x.IsEnable==true && x.Type == HomePageType.Pages).OrderByDescending(y => y.CreatedDate);
            var listLinks = _context.IvsVisaPages.Where(x => x.IsEnable==true && x.Type == HomePageType.Links).OrderByDescending(y => y.CreatedDate);
            var quickcontactinfo = _context.IvsVisaQuickContactInfo.ToList();
            ViewBag.PagesOurContent = listPages.ToList();
            ViewBag.LinksOurContent = listLinks.ToList();
            ViewBag.QuickContactInfo = quickcontactinfo;

            var countryIso = (from iso in _context.IvsVisaCountries where iso.CountryName.Contains(countryName) select iso.CountryIso).FirstOrDefault();

            var checkDiplomaticRepresentationData = (from dipl in _context.IvsVisaCountriesDiplomaticRepresentation select dipl.CountryIso).Contains(countryIso);

            if (checkDiplomaticRepresentationData == true)
            {
                var countryDetails = from country in _context.IvsVisaCountries
                                     join us in _context.IvsVisaCountriesDiplomaticRepresentation on country.CountryIso equals us.CountryIso
                                     where country.CountryName.Contains(countryName) //&& us.IsEnable == 1
                                     orderby us.Priority
                                     select new IvsVisaCountriesDiplomaticRepresentation
                                     {
                                         OfficeName = us.OfficeName,
                                         OfficeAddress = us.OfficeAddress,
                                         OfficeCity = us.OfficeCity,
                                         OfficeCountry = us.OfficeCountry,
                                         OfficePhone = us.OfficePhone,
                                         OfficeFax = us.OfficeFax,
                                         OfficeTimings = us.OfficeTimings,
                                         OfficeVisaTimings = us.OfficeVisaTimings,
                                         OfficeCollectionTimings = us.OfficeCollectionTimings,
                                         OfficeEmail = us.OfficeEmail,
                                         OfficeNotes = us.OfficeNotes,
                                         TerritoryJurisdiction = us.TerritoryJurisdiction,
                                         bCountryFlag = countryFlag,
                                         bCountryName = countryName,
                                         IsEnable = us.IsEnable
                                     };

                HomePage model = new HomePage();
                model.diplomaticrepresentation = countryDetails.ToList();
                model.PagesOurContentPagesList = listPages.ToList();
                model.PagesOurContentLinksList = listLinks.ToList();
                model.bCountryName = countryName;

IVSource/Views/IvsVisaCountriesDiplomaticRepresentations/Add.cshtml
@model IVSource.Models.IvsVisaCountriesDiplomaticRepresentation

@{
    ViewData["Title"] = "DIPLOMATIC REPRESENTATIONS";
    Layout = "~/Views/Shared/Admin/_LayoutAdminVisaDetails.cshtml";
}

<div class="row">
    <div class="col-md-10" style="margin:auto;">
        <h2>Add</h2>
        <hr />
        <form asp-action="Add" asp-controller="IvsVisaCountriesDiplomaticRepresentations">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SerialNum" />
            <input type="hidden" id="CountryName" name="CountryName" value="@TempData.Peek("CountryName")" />
            <div class="form-group">
                <label asp-for="OfficeName" class="control-label"></label>
                <input asp-for="OfficeName" class="form-control" />
                <span asp-validation-for="OfficeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeAddress" class="control-label"></label>
                <textarea asp-for="OfficeAddress" class="form-control"></textarea>
                <span asp-validation-for="OfficeAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeCity" class="control-label"></label>
                <input asp-for="OfficeCity" class="form-control" />
                <span asp-validation-for="OfficeCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficePincode" class="control-label"></label>
                <input asp-for="OfficePincode" type="number" class="form-control" />
                <span asp-validation-for="OfficePincode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeCountry" class="control-label"></label>
                <input asp-for="OfficeCountry" class="form-control" />
                <span asp-validation-for="OfficeCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficePhone" class="control-label"></label>
                <input asp-for="OfficePhone" class="form-control" />
                <span asp-validation-for="OfficePhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeTelephoneVisa" class="control-label"></label>
                <input asp-for="OfficeTelephoneVisa" class="form-control" />
                <span asp-validation-for="OfficeTelephoneVisa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeFax" class="control-label"></label>
                <input asp-for="OfficeFax" class="form-control" />
                <span asp-validation-for="OfficeFax" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeTimings" class="control-label"></label>
                <input asp-for="OfficeTimings" class="form-control" />
                <span asp-validation-for="OfficeTimings" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeVisaTimings" class="control-label"></label>
                <input asp-for="OfficeVisaTimings" class="form-control" />
                <span asp-validation-for="OfficeVisaTimings" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficePublicTimings" class="control-label"></label>
                <input asp-for="OfficePublicTimings" class="form-control" />
                <span asp-validation-for="OfficePublicTimings" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeCollectionTimings" class="control-label"></label>
                <input asp-for="OfficeCollectionTimings" class="form-control" />
                <span asp-validation-for="OfficeCollectionTimings" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeEmail" class="control-label"></label>
                <input asp-for="OfficeEmail" class="form-control" />
                <span asp-validation-for="OfficeEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeWebsite" class="control-label"></label>
                <input asp-for="OfficeWebsite" class="form-control" />
                <span asp-validation-for="OfficeWebsite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeNotes" class="control-label"></label>
                <input asp-for="OfficeNotes" class="form-control" />
                <span asp-validation-for="OfficeNotes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TerritoryJurisdiction" class="control-label"></label>
                <input asp-for="TerritoryJurisdiction" class="form-control" />
                <span asp-validation-for="TerritoryJurisdiction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsEnable" class="control-label"></label>
                <select asp-for="IsEnable" class="form-control">
                    <option value="1">Enable</option>
                    <option value="0">Disable</option>
                </select>
                <span asp-validation-for="IsEnable" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Priority" class="control-label"></label>
                <input asp-for="Priority" class="form-control" />
                <span asp-validation-for="Priority" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default blue-button" />
            </div>
            <div>
                <a asp-action="Index" asp-controller="IvsVisaCountriesDiplomaticRepresentations">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IVSource/Views/IvsVisaCountriesDiplomaticRepresentations/DiplomaticRepresentation.cshtml
@model IEnumerable<IVSource.Models.IvsVisaCountriesDiplomaticRepresentation>
@{
    ViewData["Title"] = "Diplomatic Representations";
    Layout = "~/Views/Shared/_LayoutMemberPage.cshtml";
}

<div id="id-1" class="penal_cont_area">
    <div class="penal_cont">
        <p style="color:black; font-size: 30px; margin-top: -18px; margin-bottom: 18px">Diplomatic Representations</p>
        @foreach (var obj in Model)
        {
            if (obj.OfficeName != null && obj.OfficeName != "")
            {
                <b>Name : </b>
                <label>@Html.DisplayFor(model => obj.OfficeName)</label>
                <br />
            }

            if (obj.OfficeAddress != null && obj.OfficeAddress != "")
            {
                <b>Address : </b>
                <label>@Html.DisplayFor(model => obj.OfficeAddress)</label>
                <br />
            }

            if (obj.OfficeCity != null && obj.OfficeCity != "")
            {
                <b>City : </b>
                <label>@Html.DisplayFor(model => obj.OfficeCity)</label>
                <br />
            }

            if (obj.OfficeCountry != null && obj.OfficeCountry != "")
            {
                <b>Country : </b>
                <label>@Html.DisplayFor(model => obj.OfficeCountry)</label>
                <br />
            }

            if (obj.OfficePhone != null && obj.OfficePhone != "")
            {
                <b>Telephone : </b>
                <label>@Html.DisplayFor(model => obj.OfficePhone)</label>
                <br />
            }

            if (obj.OfficeFax != null && obj.OfficeFax != "")
            {
                <b>Fax : </b>
                <label>@Html.DisplayFor(model => obj.OfficeFax)</label>
                <br />
            }

            if (obj.OfficeTimings != null && obj.OfficeTimings != "")
            {
                <b>Office Timings : </b>
                <label>@Html.DisplayFor(model => obj.OfficeTimings)</label>
                <br />
            }

            if (obj.OfficeVisaTimings != null && obj.OfficeVisaTimings != "")
            {
                <b>Visa Timings : </b>
                <label>@Html.DisplayFor(model => obj.OfficeVisaTimings)</label>
                <br />
            }

            if (obj.OfficeCollectionTimings != null && obj.OfficeCollectionTimings != "")
            {
                <b>Collection Timings : </b>
                <label>@Html.DisplayFor(model => obj.OfficeCollectionTimings)</label>
                <br />
            }

            if (obj.OfficeEmail != null && obj.OfficeEmail != "")
            {
                <b>Email : </b>
                <label>@Html.DisplayFor(model => obj.OfficeEmail)</label>
                <br />
            }

            if (obj.OfficeNotes != null && obj.OfficeNotes != "")
            {
                <b>Notes : </b>
                <label>@Html.DisplayFor(model => obj.OfficeNotes)</label>
                <br />
            }

            if (obj.TerritoryJurisdiction != null && obj.TerritoryJurisdiction != "")
            {
                <b>Territory Jurisdiction : </b>
                <label>@Html.DisplayFor(model => obj.TerritoryJurisdiction)</label>
                <br />
                <br />
            }
        }
    </div>
</div>

IVSource/Views/IvsVisaCountriesDiplomaticRepresentations/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<IVSource.Models.IvsVisaCountriesDiplomaticRepresentation>
@using ReflectionIT.Mvc.Paging
@addTagHelper *,ReflectionIT.Mvc.Paging

@{
    ViewData["Title"] = "DIPLOMATIC REPRESENTATIONS";
    Layout = "~/Views/Shared/Admin/_LayoutAdminVisaDetails.cshtml";
}
@{if (TempData["Message"] != null)
    {
        <h4 class="text-center" style="color:green;">@TempData["Message"]</h4>
        <br />
    }
}

<div class="container">
    <div class="col-md-10" style="margin:auto;">
        <div class="form-group row">
            <div class="col-md-6">
                <div>
                    <a asp-action="Add" asp-controller="IvsVisaCountriesDiplomaticRepresentations" class="btn btn-info form-control text-white" style="width:200px; margin-top: 0.9em;">
                        Add New Diplomatic Representation
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="font-weight-bold col-sm-6">
                Total : @ViewBag.Total
            </div><br />
        </div>
        <div class="row">
            <div class="col-sm-6">
                <label class="lead">  Show entries &nbsp;</label>
                @Html.DropDownList("rowsToShow", new List<SelectListItem>
                {
                  new SelectListItem { Text = "10", Value = "10"},
                  new SelectListItem { Text = "25", Value = "25"},
                  new SelectListItem { Text = "50", Value = "50"},
                  new SelectListItem { Text = "100", Value = "100"}
                })
            </div>
            <div class="col-sm-6 text-right">
                <form method="get" class="form-inline" style="display: inline-block;">
                    <input name="filter" class="form-control"
                           value="@Model.RouteValue["Filter"]" />  &nbsp; &nbsp;
                    <button type="submit" class="btn btn-info">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
                    </button>
                </form>
            </div>
        </div>
        <div class="clear"></div>
        <br />
        <br />
        <table class="table table-bordered table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>
                        @Html.SortableHeaderFor(model => model.OfficeName)
                    </th>
                    <th>
                        @Html.SortableHeaderFor(model => model.OfficeCity)
                    </th>
                    <th>
                        @Html.SortableHeaderFor(model => model.OfficeCountry)
                    </th>
                    <th>
                        @Html.SortableHeaderFor(model => model.IsEnable)
                    </th>
                    <th>
                        @Html.SortableHeaderFor(model => model.Priority)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Select((value, index) => new { value, index }))
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.value.OfficeName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.value.OfficeCity)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.value.OfficeCountry)
                        </td>
                        <td>
                            @(Convert.ToBoolean(item.value.IsEnable) ? "Yes" : "No")
                        </td>
                        <td>@Html.DisplayFor(modelItem => item.value.Priority)</td>
                        <td class="subsBtn">
                            <a asp-action="Edit" asp-route-id="@item.value.SerialNum">Edit</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <nav aria-label="pagination">
            <vc:pager paging-list="@Model" />
        </nav>
        @section Scripts {
            <script>
                jQuery('#rowsToShow').change(function () {
                    var currentUrl = jQuery(location).attr('href');
                    var url;
                    if (currentUrl.indexOf("?") != -1) {
                        if (currentUrl.indexOf("rowsToShow") != -1) {
                            var href = new URL(currentUrl);
                            href.searchParams.set('rowsToShow', jQuery(this).val());
                            url = href.toString();
                        }
                        else
                            url = currentUrl + "&rowsToShow=" + jQuery(this).val();
                    }
                    else
                        url = currentUrl + "?rowsToShow=" + jQuery(this).val();
                    window.location.href = url;
                });
            </script>
        }
    </div>
</div>