IVSource/Controllers/IvsVisaHelpAddressesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IVSource.Models;
using ReflectionIT.Mvc.Paging;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Authorization;
using System.Text.RegularExpressions;
using AllPageLogout.Filter;

namespace IVSource.Controllers
{
    [Authorize(Roles = MemberType.MemberAdmin, AuthenticationSchemes = MemberType.MemberAdminAuth)]
    public class IvsVisaHelpAddressesController : Controller
    {
        private readonly IVSourceContext _context;

        public IvsVisaHelpAddressesController(IVSourceContext context)
        {
            _context = context;
        }

        // GET: IvsVisaHelpAddresses
        public async Task<IActionResult> Index(string filter, string rowsToShow = "10", int page = 1, string sortExpression = "SerialNum")
        {
            var allList = _context.IvsVisaHelpAddress.Where(x => x.CountryIso == TempData.Peek("CountryIso").ToString()); //.ToListAsync();

            if (!string.IsNullOrWhiteSpace(filter))
            {
                allList = allList.Where(p => filter.ToLower() == "yes" ? (p.IsEnable == 1) : (filter.ToLower() == "no" ? (p.IsEnable == 0) :
                        (p.OfficeName.Contains(filter) || p.OfficeCountry.Contains(filter) || p.AddressType.Contains(filter)))).OrderByDescending(y => y.SerialNum);
            }
            else
                allList = allList.OrderByDescending(y => y.SerialNum);

            int count = allList.Count();
            ViewBag.Total = count;

            var model = await PagingList<IvsVisaHelpAddress>.CreateAsync(allList, Convert.ToInt16(rowsToShow), page, sortExpression, "SerialNum");
            model.RouteValue = new RouteValueDictionary { { "filter", filter }, { "rowsToShow", rowsToShow } };
            return View(model);
        }

        // GET: IvsVisaHelpAddresses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ivsVisaHelpAddress = await _context.IvsVisaHelpAddress.FindAsync(id);
            if (ivsVisaHelpAddress == null)
            {
                return NotFound();
            }
            return View(ivsVisaHelpAddress);
        }

        // POST: IvsVisaHelpAddresses/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, string CountryName, [Bind("SerialNum,CountryIso,OfficeId,OfficeName,OfficeAddress,OfficeCity,OfficePincode,OfficeCountry,OfficePhone,OfficeFax,OfficeEmail,OfficeWebsite,OfficeUrl,OfficeNotes,AddressType,IsEnable,CreatedDate,ModifiedDate")] IvsVisaHelpAddress ivsVisaHelpAddress)
        {
            if (id != ivsVisaHelpAddress.SerialNum)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    ivsVisaHelpAddress.ModifiedDate = DateTime.Now;
                    _context.Update(ivsVisaHelpAddress);
                    _context.Entry(ivsVisaHelpAddress).Property(x => x.SerialNum).IsModified = false;
                    _context.Entry(ivsVisaHelpAddress).Property(x => x.CountryIso).IsModified = false;
                    _context.Entry(ivsVisaHelpAddress).Property(x => x.OfficeId).IsModified = false;
                    _context.Entry(ivsVisaHelpAddress).Property(x => x.CreatedDate).IsModified = false;

                    var upCountry = _context.IvsVisaCountries.Where(y => y.CountryName == CountryName).FirstOrDefault();
                    upCountry.IsUpdated = 1;
                    upCountry.ModifiedDate = DateTime.Now;
                    _context.Update(upCountry);

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IvsVisaHelpAddressExists(ivsVisaHelpAddress.SerialNum))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["Message"] = "Updated Successfully!";
                return RedirectToAction("Index");
            }
            return View(ivsVisaHelpAddress);
        }

        private bool IvsVisaHelpAddressExists(int id)
        {
            return _context.IvsVisaHelpAddress.Any(e => e.SerialNum == id);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(IvsVisaHelpAddress obj)
        {
            string country = TempData.Peek("CountryName").ToString();
            var countryIso = _context.IvsVisaCountries.FirstOrDefault(x => x.CountryName == country);

            var ran = RandomString(8);
            var oid = ran;

            obj.CountryIso = countryIso.CountryIso;
            obj.OfficeId = "HA" + oid;
            obj.CreatedDate = DateTime.Now;
            obj.ModifiedDate = DateTime.Now;

            _context.IvsVisaHelpAddress.Add(obj);
            _context.SaveChanges();
            TempData["Message"] = "Inserted Successfully!";
            return RedirectToAction("../IvsVisaHelpAddresses/Index");
        }

        Random random = new Random();
        public string RandomString(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length).Select(s => s[random.Next(s.Length)]).ToArray());
        }
    }

    //[Authorize(Roles = MemberType.MemberUser, AuthenticationSchemes = MemberType.MemberUserAuth)]
    public class IvsVisaHelpAddresses_UserController : Controller
    {
        private readonly IVSourceContext _context;

        public IvsVisaHelpAddresses_UserController(IVSourceContext context)
        {
            _context = context;
        }
        [CustemFilter]
        public IActionResult Indian_Mission_Overseas(string page, string countryName, string countryFlag)
        {
            var countryIso = (from iso in _context.IvsVisaCountries where iso.CountryName.Contains(countryName) select iso.CountryIso).FirstOrDefault();           

            var checkIndianMissionOverseasData = (from indi in _context.IvsVisaHelpAddress
                                                  where indi.CountryIso == countryIso
                                                  select indi.AddressType).Contains("IMO");

            var listPages = _context.IvsVisaPages.Where(x => x.IsEnable==true && x.Type == HomePageType.Pages).OrderByDescending(y => y.CreatedDate);
            var listLinks = _context.IvsVisaPages.Where(x => x.IsEnable==true && x.Type == HomePageType.Links).OrderByDescending(y => y.CreatedDate);
            var quickcontactinfo = _context.IvsVisaQuickContactInfo.ToList();
            ViewBag.PagesOurContent = listPages.ToList();
            ViewBag.LinksOurContent = listLinks.ToList();
            ViewBag.QuickContactInfo = quickcontactinfo;

            if (checkIndianMissionOverseasData == true)
            {
                var countryDetails =  from country in _context.IvsVisaCountries
                                      join us in _context.IvsVisaHelpAddress on country.CountryIso equals us.CountryIso
                                      where country.CountryName.Contains(countryName) && us.AddressType == "IMO" //&& us.IsEnable == 1
                                      select new IvsVisaHelpAddress
                                      {
                                          OfficeName = us.OfficeName,
                                          OfficeAddress = us.OfficeAddress,
                                          OfficeCity = us.OfficeCity.Replace("\\n", string.Empty),
                                          OfficeCountry = us.OfficeCountry,
                                          OfficePhone = us.OfficePhone,
                                          OfficeFax = us.OfficeFax,
                                          OfficeEmail = us.OfficeEmail,
                                          OfficeWebsite = us.OfficeWebsite,
                                          bCountryFlag = countryFlag,
                                          bCountryName = countryName,
                                          IsEnable = us.IsEnable
                                      };


                HomePage model = new HomePage();
                model.helpaddress = countryDetails.ToList();
                model.PagesOurContentPagesList = listPages.ToList();
                model.PagesOurContentLinksList = listLinks.ToList();
                model.bCountryName = countryName;
                model.bCountryFlag = countryFlag;
                List<HomePage> allData = new List<HomePage>();
                allData.Add(model);
                return View("Indian_Mission_Overseas", allData);
            }
            else
            {
                IvsVisaHelpAddress obj = new IvsVisaHelpAddress();
                obj.bCountryFlag = countryFlag;
                obj.bCountryName = countryName;
                ViewBag.Page = page;
                return View("IndianMissionOverseas", obj);
            }
        }

        
        public IActionResult Indian_Mission_Overseasr(string countryName, string countryFlag)
        {
            var countryIso = (from iso in _context.IvsVisaCountries where iso.CountryName.Contains(countryName) select iso.CountryIso).FirstOrDefault();

            var countryr = (from info in _context.IvsVisaCountries where info.CountryName.Contains(countryName) select info.Country).FirstOrDefault();

            countryr = countryr.Replace(System.Environment.NewLine, string.Empty);

IVSource/Views/IvsVisaHelpAddresses/Add.cshtml
@model IVSource.Models.IvsVisaHelpAddress

@{
    ViewData["Title"] = "HELP ADDRESSES";
    Layout = "~/Views/Shared/Admin/_LayoutAdminVisaDetails.cshtml";
}

<div class="row">
    <div class="col-md-10" style="margin:auto;">
        <h2>Add</h2>
        <hr />
        <form asp-action="Add" asp-controller="IvsVisaHelpAddresses">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" id="CountryName" name="CountryName" value="@TempData.Peek("CountryName")" />
            <input type="hidden" asp-for="SerialNum" />
            <div class="form-group">
                <label asp-for="OfficeName" class="control-label"></label>
                <input asp-for="OfficeName" class="form-control" />
                <span asp-validation-for="OfficeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeAddress" class="control-label"></label>
                <textarea asp-for="OfficeAddress" class="form-control"></textarea>
                <span asp-validation-for="OfficeAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeCity" class="control-label"></label>
                <input asp-for="OfficeCity" class="form-control" />
                <span asp-validation-for="OfficeCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficePincode" class="control-label"></label>
                <input asp-for="OfficePincode" class="form-control" />
                <span asp-validation-for="OfficePincode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeCountry" class="control-label"></label>
                <input asp-for="OfficeCountry" class="form-control" />
                <span asp-validation-for="OfficeCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficePhone" class="control-label"></label>
                <input asp-for="OfficePhone" class="form-control" />
                <span asp-validation-for="OfficePhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeFax" class="control-label"></label>
                <input asp-for="OfficeFax" class="form-control" />
                <span asp-validation-for="OfficeFax" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeEmail" class="control-label"></label>
                <input asp-for="OfficeEmail" class="form-control" />
                <span asp-validation-for="OfficeEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeWebsite" class="control-label"></label>
                <input asp-for="OfficeWebsite" class="form-control" />
                <span asp-validation-for="OfficeWebsite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeUrl" class="control-label"></label>
                <input asp-for="OfficeUrl" class="form-control" />
                <span asp-validation-for="OfficeUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeNotes" class="control-label"></label>
                <input asp-for="OfficeNotes" class="form-control" />
                <span asp-validation-for="OfficeNotes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddressType" class="control-label"></label>
                <select asp-for="AddressType" class="form-control">
                    <option value="IHA">International Help Addresses</option>
                    <option value="IMO">Indian Missions Overseas</option>
                </select>
                <span asp-validation-for="AddressType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsEnable" class="control-label"></label>
                <select asp-for="IsEnable" class="form-control">
                    <option value="1">Enable</option>
                    <option value="0">Disable</option>
                </select>
                <span asp-validation-for="IsEnable" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default blue-button" />
            </div>
            <div>
                <a asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IVSource/Views/IvsVisaHelpAddresses/Edit.cshtml
@model IVSource.Models.IvsVisaHelpAddress

@{
    ViewData["Title"] = "HELP ADDRESSES";
    Layout = "~/Views/Shared/Admin/_LayoutAdminVisaDetails.cshtml";
}

<div class="row">
    <div class="col-md-10" style="margin:auto;">
        <h2>Update </h2>
        <hr />
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" id="CountryName" name="CountryName" value="@TempData.Peek("CountryName")" />
            <input type="hidden" asp-for="SerialNum" />
            <div class="form-group">
                <label asp-for="OfficeName" class="control-label"></label>
                <input asp-for="OfficeName" class="form-control" />
                <span asp-validation-for="OfficeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeAddress" class="control-label"></label>
                <input asp-for="OfficeAddress" class="form-control" />
                <span asp-validation-for="OfficeAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeCity" class="control-label"></label>
                <input asp-for="OfficeCity" class="form-control" />
                <span asp-validation-for="OfficeCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficePincode" class="control-label"></label>
                <input asp-for="OfficePincode" class="form-control" />
                <span asp-validation-for="OfficePincode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeCountry" class="control-label"></label>
                <input asp-for="OfficeCountry" class="form-control" />
                <span asp-validation-for="OfficeCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficePhone" class="control-label"></label>
                <input asp-for="OfficePhone" class="form-control" />
                <span asp-validation-for="OfficePhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeFax" class="control-label"></label>
                <input asp-for="OfficeFax" class="form-control" />
                <span asp-validation-for="OfficeFax" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeEmail" class="control-label"></label>
                <input asp-for="OfficeEmail" class="form-control" />
                <span asp-validation-for="OfficeEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeWebsite" class="control-label"></label>
                <input asp-for="OfficeWebsite" class="form-control" />
                <span asp-validation-for="OfficeWebsite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeUrl" class="control-label"></label>
                <input asp-for="OfficeUrl" class="form-control" />
                <span asp-validation-for="OfficeUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeNotes" class="control-label"></label>
                <input asp-for="OfficeNotes" class="form-control" />
                <span asp-validation-for="OfficeNotes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddressType" class="control-label"></label>
                <select asp-for="AddressType" class="form-control">
                    <option value="IHA">International Help Addresses</option>
                    <option value="IMO">Indian Missions Overseas</option>
                </select>
                <span asp-validation-for="AddressType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsEnable" class="control-label"></label>
                <select asp-for="IsEnable" class="form-control">
                    <option value="1">Enable</option>
                    <option value="0">Disable</option>
                </select>
                <span asp-validation-for="IsEnable" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-default blue-button" />
            </div>
            <div>
                <a asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IVSource/Views/IvsVisaHelpAddresses/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<IVSource.Models.IvsVisaHelpAddress>
@using ReflectionIT.Mvc.Paging
@addTagHelper *,ReflectionIT.Mvc.Paging

@{
    ViewData["Title"] = "HELP ADDRESSES";
    Layout = "~/Views/Shared/Admin/_LayoutAdminVisaDetails.cshtml";
}

<div class="container">
    <div class="col-md-10" style="margin:auto;">
        @{if (TempData["Message"] != null)
            {
                <h4 class="text-center" style="color:green;">@TempData["Message"]</h4>
                <br />
            }
        }
        <div class="form-group row">
            <div class="col-md-6">
                <div>
                    <a asp-action="Add" asp-controller="IvsVisaHelpAddresses" class="btn btn-info form-control text-white" style="width:200px; margin-top: 0.9em;">
                        Add New Help Address
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="font-weight-bold col-sm-6">
                Total : @ViewBag.Total
            </div><br />
        </div>
        <div class="row">
            <div class="col-sm-6">
                <label class="lead">  Show entries &nbsp;</label>
                @Html.DropDownList("rowsToShow", new List<SelectListItem>
                {
                  new SelectListItem { Text = "10", Value = "10"},
                  new SelectListItem { Text = "25", Value = "25"},
                  new SelectListItem { Text = "50", Value = "50"},
                  new SelectListItem { Text = "100", Value = "100"}
                })
            </div>
            <div class="col-sm-6 text-right">
                <form method="get" class="form-inline" style="display: inline-block;">
                    <input name="filter" class="form-control"
                           value="@Model.RouteValue["Filter"]" />  &nbsp; &nbsp;
                    <button type="submit" class="btn btn-info">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
                    </button>
                </form>
            </div>
        </div>
        <div class="clear"></div>
        <br />
        <br />
        <table class="table table-bordered table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>
                        @Html.SortableHeaderFor(model => model.OfficeName)
                    </th>
                    <th>
                        @Html.SortableHeaderFor(model => model.OfficeCountry)
                    </th>
                    <th>
                        @Html.SortableHeaderFor(model => model.AddressType)
                    </th>
                    <th>
                        @Html.SortableHeaderFor(model => model.IsEnable)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Select((value, index) => new { value, index }))
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.value.OfficeName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.value.OfficeCountry)
                        </td>
                        <td>
                            @(item.value.AddressType == "IHA" ? "International Help Addresses" : "Indian Missions Overseas")
                        </td>
                        <td>
                            @(Convert.ToBoolean(item.value.IsEnable) ? "Yes" : "No")
                        </td>
                        <td class="subsBtn">
                            <a asp-action="Edit" asp-route-id="@item.value.SerialNum">Edit</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <nav aria-label="pagination">
            <vc:pager paging-list="@Model" />
        </nav>
        @section Scripts {
            <script>
                jQuery('#rowsToShow').change(function () {
                    var currentUrl = jQuery(location).attr('href');
                    var url;// = currentUrl + "?rowsToShow=" + jQuery(this).val();
                    if (currentUrl.indexOf("?") != -1) {
                        if (currentUrl.indexOf("rowsToShow") != -1) {
                            var href = new URL(currentUrl);
                            href.searchParams.set('rowsToShow', jQuery(this).val());
                            url = href.toString();
                        }
                        else
                            url = currentUrl + "&rowsToShow=" + jQuery(this).val();
                    }
                    else
                        url = currentUrl + "?rowsToShow=" + jQuery(this).val();
                    window.location.href = url;
                });
            </script>
        }
    </div>
</div>

IVSource/Views/IvsVisaHelpAddresses/Indian_Mission_Overseas.cshtml
@model IEnumerable<IVSource.Models.IvsVisaHelpAddress>
@{
    ViewData["Title"] = "Indian Mission Overseas";
    Layout = "~/Views/Shared/_LayoutMemberPage.cshtml";
}
<h2 style="color:black; margin-top:-2%;">Indian Mission Overseas</h2>
<div>
    @foreach (var x in Model)
    {
        @if (x.OfficeName != null && x.OfficeName != "")
        {
            <p><b>Name:</b>  @Html.DisplayFor(model => x.OfficeName)</p>
        }
        @if (x.OfficeAddress != null && x.OfficeAddress != "")
        {
            <p><b>Address:</b>  @Html.DisplayFor(model => x.OfficeAddress)</p>
        }

        @if (x.OfficeCity != null && x.OfficeCity != "")
        {
            <p><b>City:</b> @Html.DisplayFor(model => x.OfficeCity)</p>
        }
        @if (x.OfficeCountry != null && x.OfficeCountry != "")
        {
            <p><b>Country:</b> @Html.DisplayFor(model => x.OfficeCountry)</p>
        }
        @if (x.OfficePhone != null && x.OfficePhone != "")
        {
            <p><b>Telephone:</b> @Html.DisplayFor(model => x.OfficePhone)</p>
        }

        @if (x.OfficeFax != null && x.OfficeFax != "")
        {
            <p><b>Fax:</b> @Html.DisplayFor(model => x.OfficeFax)</p>
        }

        @if (x.OfficeEmail != null && x.OfficeEmail != "")
        {
            <p><b>Email:</b> @Html.DisplayFor(model => x.OfficeEmail)</p>
        }

        @if (x.OfficeWebsite != null && x.OfficeWebsite != "")
        {
            // <p><b>Website:</b>  @Html.DisplayFor(model => x.OfficeWebsite) <br /><br /></p>
          <p><b>Website:</b> <a href="//@x.OfficeWebsite.Replace(" ", "")" target="_blank"> @Html.DisplayFor(model => x.OfficeWebsite) </a><br /><br /></p>

        }
        <br />
        <br />
    }
</div>

IVSource/Views/IvsVisaHelpAddresses/International_Help_Address.cshtml
@model IEnumerable<IVSource.Models.IvsVisaHelpAddress>
@{
    ViewData["Title"] = "International Help Address";
    Layout = "~/Views/Shared/_LayoutMemberPage.cshtml";
}
<h2 style="color:black; margin-top:-2%;">International Help Address</h2>
<div>
    @foreach (var x in Model)
    {
        @if (x.OfficeName != null && x.OfficeName != "")
        {
            <p><b>Name:</b>  @Html.DisplayFor(model => x.OfficeName)</p>
        }
        @if (x.OfficeAddress != null && x.OfficeAddress != "")
        {
            <p><b>Address: </b>  @Html.DisplayFor(model => x.OfficeAddress)</p>
        }

        @if (x.OfficeCity != null && x.OfficeCity != "")
        {
            <p><b>City:</b>  @Html.DisplayFor(model => x.OfficeCity)</p>
        }
        @if (x.OfficeCountry != null && x.OfficeCountry != "")
        {
            <p><b>Country:</b>  @Html.DisplayFor(model => x.OfficeCountry)</p>
        }
        @if (x.OfficePhone != null && x.OfficePhone != "")
        {
            <p><b>Telephone:</b>  @Html.DisplayFor(model => x.OfficePhone)</p>
        }
        @if (x.OfficeFax != null && x.OfficeFax != "")
        {
            <p><b>Fax:</b>  @Html.DisplayFor(model => x.OfficeFax)</p>
        }
        @if (x.OfficeEmail != null && x.OfficeEmail != "")
        {
            <p><b>Email:</b>  @Html.DisplayFor(model => x.OfficeEmail)</p>
        }
        @if (x.OfficeWebsite != null && x.OfficeWebsite != "")
        {
            <p><b>Website:</b> <a href="//@x.OfficeWebsite.Replace(" ", "")" target="_blank"> @Html.DisplayFor(model => x.OfficeWebsite) </a><br /><br /></p>
        }
        <br /><br />
    }

</div>